### ISSUE TITLE
SRWebsocket - NSStreamEventEndEncontered

### ISSUE THREAD

**Issue by subbu11** [square/SocketRocket#113]
Sir , while sending a message to the websocket server , after the data transfer is completed , I get NSStreamEventEndEncountered . Due to this , the websocket gets closed .
Sir , I have searched a lot on internet but dint get a solution to the problem . Please tell  what is the problem and the solution for it as early as possible .

**Comment by mikelikespie** [comment]
Doing some housekeeping. Please reopen if still relevant
