### ISSUE TITLE
Type conversion warning in SRWebSocket.m

### ISSUE THREAD

**Issue by jasonmccreary** [square/SocketRocket#115]
I receive the following warning

> SocketRocket/SRWebSocket.m:923:55: Implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'size_t' (aka 'unsigned long')

`payload_length` is defined as a `uint64_t`. In all but one place (line 1034) it is used as a `size_t`. However, simply converting it to a `size_t` issues a warning for the line:

    header.payload_length = EndianU64_BtoN(*(uint64_t *)(mapped_buffer));

**Comment by mikelikespie** [comment]
Doing some housekeeping. Please reopen if still relevant
