### ISSUE TITLE
Getting error "_MessageSetHeaderFieldValue", referenced from:       -[SRWebSocket didConnect] in SRWebSocket.o

### ISSUE THREAD

**Issue by sandy99** [square/SocketRocket#118]
![screen shot 2013-09-30 at 4 36 13 pm](https://f.cloud.github.com/assets/1879847/1236532/174f103a-29c3-11e3-9e9c-84ab8eb693e6.png)
I added all the framework but still getting error , please reply me where i am wrong , My project is ARC enable

ld: warning: ignoring file /Users/hytechpro/Engineering/EvenSteven/trunk/development/code/iOS/EvenSteven/EvenSteven/ESSocket/libSocketRocket_iPhone.a, missing required architecture i386 in file /Users/hytechpro/Engineering/EvenSteven/trunk/development/code/iOS/EvenSteven/EvenSteven/ESSocket/libSocketRocket_iPhone.a (2 slices)
Undefined symbols for architecture i386:
  "_MessageSetHeaderFieldValue", referenced from:
      -[SRWebSocket didConnect] in SRWebSocket.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by mikelikespie** [comment]
Doing some housekeeping. Please reopen if still relevant
