### ISSUE TITLE
Memory Leak..

### ISSUE THREAD

**Issue by kodjobaah** [square/SocketRocket#121]
Hi,

In the following:

- (void)_writeData:(NSData *)data;
{    
    [self assertOnWorkQueue];

    if (_closeWhenFinishedWriting) {
            return;
    }
    [_outputBuffer appendData:data];
    [self _pumpWriting];
}

The outputBuffer keeps growing..and it is causing my application to crash...
I have attached a snap shot
![screen shot 2013-10-15 at 12 48 56](https://f.cloud.github.com/assets/1099467/1332933/ed35d65a-3587-11e3-9710-dc9a2fd4d9bd.png)

**Comment by mikelikespie** [comment]
Doing some housekeeping. Please reopen if still relevant
