### ISSUE TITLE
NSStreamDelegate method stream:handleEvent: not called

### ISSUE THREAD

**Issue by andrewarrow** [square/SocketRocket#122]
I got SocketRocket all compiling in my project but when I make a connection nothing happens.  I tracked down the issue to the stream:handleEvent: method is never called.  Found this stackoverflow issue:

http://stackoverflow.com/questions/4930957/nsstream-and-sockets-nsstreamdelegate-methods-not-being-called

They say change [NSRunLoop currentRunLoop] to [NSRunLoop mainRunLoop] but that doesn't work.  I know you said in the README you are still working on:

"Move the streams off the main runloop (most of the work is backgrounded uses GCD, but I just haven't gotten around to moving it off the main loop since I converted it from dispatch_io)"

but just thought I'd ask is there a quick fix I can do I get stream:handleEvent called?

**Comment by mikelikespie** [comment]
Doing some housekeeping. Please reopen if still relevant
