### ISSUE TITLE
Undefined symbols for architecture i386: "_utf8_nextCharSafeBody"

### ISSUE THREAD

**Issue by yirenjun** [square/SocketRocket#128]
0.3.1-beta2

![snip20131026_84](https://f.cloud.github.com/assets/273997/1409283/3fa5afcc-3d90-11e3-968d-b8459000cff0.png)
![snip20131026_85](https://f.cloud.github.com/assets/273997/1409284/3fa89d2c-3d90-11e3-9b4a-2e095a146401.png)

**Comment by flashspys** [comment]
Fixed the issue for me, too. Maybe somebody should mention that in the readme.
