### ISSUE TITLE
delegate dispatch queue not on main queue OK?

### ISSUE THREAD

**Issue by chadbag** [square/SocketRocket#130]
Forgive me for maybe a stupid question.  I have not delved into the intricacies of the code.  I am using https://github.com/pkyeck/socket.IO-objc  which uses SocketRocket.

In doing so, I noticed that the calls that notify me of new data that came in run on the main  thread.  This is causing blocking as we download images and stuff to the phone over the socket.

I was wondering why a worker queue or something is not being used.  I found in SRWebSocket.m, `-(void)_SR_commonInit` the line

   `_delegateDispatchQueue = dispatch_get_main_queue();`

which I changed to

   `_delegateDispatchQueue = dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0);`

This runs the callbacks on a thread other than the main thread (technically non main queue)  and seems to work fine in my app with some minimal testing.  Not knowing the  whole architecture of SocketRocket I wanted to make sure this would not cause subtle problems down the road.

Thanks
Chad

**Comment by mikelikespie** [comment]
It should be a serial queue. Can't use a global queue.
