### ISSUE TITLE
Warning: SRWebSocket.m:923:55: Implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'size_t' (aka 'unsigned long')

### ISSUE THREAD

**Issue by Elshad** [square/SocketRocket#141]
Change row 923 as below:
[self _addConsumerWithDataLength:(size_t)frame_header.payload_length callback:^(SRWebSocket *self, NSData *newData) {

**Comment by mikelikespie** [comment]
Doing some housekeeping. Please reopen if still relevant
