### ISSUE TITLE
EXC_BAD_ACCESS: socketData is nil

### ISSUE THREAD

**Issue by jowie** [square/SocketRocket#171]
EXC_BAD_ACCESS, Line 1380 of SRWebSocket.m (stream:handleEvent:)

On the CFDataGetBytes line

eventCode was NSStreamEventOpenCompleted
aStream was an NSCFInputStream object
socket was 1
socketData was 0x0

Sorry can't give any more details than that!

**Comment by mikelikespie** [comment]
Doing some housekeeping. Please reopen if still relevant
