### ISSUE TITLE
Connection problem with sending SSL / TLS certificate to the server (not possible to send it)

### ISSUE THREAD

**Issue by AmirovT** [square/SocketRocket#188]
I'm using this wonderful library and found a connection problem with sending SSL / TLS certificate to the server (not possible to send it). Can I change a little your sources, and add a method that will receive a certificate from the NSBundle and putting it into the output stream?
Thank you.

**Comment by mikelikespie** [comment]
Doing some housekeeping. Please reopen if still relevant
