### ISSUE TITLE
Socket is disconnecting after some time.

### ISSUE THREAD

**Issue by AkshayNalawade** [square/SocketRocket#189]
Hi Everyone,

My socket is disconnecting after some time when connection is established.

**Following are logs**-
[SR] NSStreamEventOpenCompleted <__NSCFInputStream: 0x117898a0>
[SR] Connected
[SR] NSStreamEventOpenCompleted <__NSCFOutputStream: 0xacb9150>
[SR] NSStreamEventHasSpaceAvailable 
[SR] Failing with error Error writing to stream
Error : ConnectionError
[SR] Trying to disconnect
[SR] connectTimeout

Also, can some one please tell me under which conditions 'Error writing to stream' error occurs?

**Comment by mikelikespie** [comment]
Doing some housekeeping. Please reopen if still relevant
