### ISSUE TITLE
build with warning

### ISSUE THREAD

**Issue by swtlovewtt** [square/SocketRocket#195]
/Users/songwt/Documents/MyRepositories/SocketRocket/SocketRocket/SRWebSocket.m:1335:47: Array access (from variable 'unmasked_payload') results in a null pointer dereference

/Users/songwt/Documents/MyRepositories/SocketRocket/SocketRocket/SRWebSocket.m:502:24: 'base64Encoding' is deprecated: first deprecated in OS X 10.9

/Users/songwt/Documents/MyRepositories/SocketRocket/SocketRocket/SRWebSocket.m:1655:32: Implicit conversion loses integer precision: 'unsigned long' to 'int32_t' (aka 'int')

**Comment by dfed** [comment]
The warning has been resolved.
