### ISSUE TITLE
Not Working in iOS 8

### ISSUE THREAD

**Issue by shaunmobrien** [square/SocketRocket#199]
I just fired up my app in Xcode 6 using a simulator with iOS 8 and I am having trouble receiving web socket messages.  It works at first but then the messages stop flowing.  The app works perfectly under iOS 7.  I have copied the .h and .m files directly to my project and do have the -ObjC other linker flag.  I just tried the latest version without luck.  I also tried making CFNetwork optional.  Anyone else having this problem?

**Comment by mikelikespie** [comment]
Doing some house keeping. Please reopen this if you're still experiencing issues.
