### ISSUE TITLE
New release anytime soon?

### ISSUE THREAD

**Issue by rahulsh1** [square/SocketRocket#202]
Any chance of releasing a new version with the latest branch?
Last release seems to be quite a while back (Jan 12, 2013)

Appreciate the efforts. Thanks

**Comment by AkshayNalawade** [comment]
+1

**Comment by sgourichon** [comment]
+1

**Comment by pbihler** [comment]
+1, especially after having fixed #226

**Comment by carloe** [comment]
+1

**Comment by shams-ahmed** [comment]
+1

**Comment by thbaja** [comment]
+1

**Comment by fatuhoku** [comment]
+1

**Comment by galambalazs** [comment]
+1

**Comment by GorkaMM** [comment]
+1

**Comment by shams-ahmed** [comment]
I ended up using the development branch, has few new features and also fixes loads of bugs. only downside is the socket connection doesn't close in some situation, so i had to handle that myself.

see https://github.com/SimplifydigitalLtd/SignalR-ObjC

pod 'SignalR-ObjC', :git => 'https://github.com/SimplifydigitalLtd/SignalR-ObjC.git', :branch => 'feature-2.0.0.beta1'

**Comment by thbaja** [comment]
Maybe this could be interesting as an alternative: https://github.com/acmacalister/jetfire
It also has a Swift counterpart.

**Comment by dfed** [comment]
We're tagging master with a new release version later today. Thanks for your patience!
