### ISSUE TITLE
Application is showing Logic error while building

### ISSUE THREAD

**Issue by jp-dubey07** [square/SocketRocket#204]
I'm getting Logic error while building application in SRWebSokcet.m file.
![screen shot 2014-10-10 at 12 03 07 pm](https://cloud.githubusercontent.com/assets/5441735/4588636/5936ab4c-5047-11e4-9508-0c8afcae02fd.png)

**Comment by mikelikespie** [comment]
Doing some house keeping. Please reopen this if you're still experiencing issues.
