### ISSUE TITLE
NSPOSIXErrorDomain

### ISSUE THREAD

**Issue by chokri** [square/SocketRocket#218]
Hi, I just changed the host to a Netty server but I failed to connect on it with this error:
TestChat[8556:287552] :( Websocket Failed With Error Error Domain=NSPOSIXErrorDomain Code=61 "The operation couldn’t be completed. Connection refused"
on Netty it shows me this error to:
[nioEventLoopGroup-3-4] WARN com.corundumstudio.socketio.handler.AuthorizeHandler - Blocked wrong request! url: /, ip...

Can Anyone help?

**Comment by mikelikespie** [comment]
Doing some house keeping. Please reopen this if you're still experiencing issues.
