### ISSUE TITLE
readyState not set initially to SR_CLOSED

### ISSUE THREAD

**Issue by cerupcat** [square/SocketRocket#223]
Currently, the readyState initial state is set to SR_CONNECTING instead of SR_CLOSED since the enum 0 state is SR_CONNECTING. This causes an issue calling "close" when the state is really SR_CLOSED but readyState thinks its SR_CONNECTING.

**Comment by mikelikespie** [comment]
I agree this isn't ideal, but the state is intended to advance.

I modeled the state machine after https://w3c.github.io/websockets/#dom-websocket-readystate
