### ISSUE TITLE
Assertion failed: (dispatch_get_specific((__bridge void *)self) == maybe_bridge(_workQueue))

### ISSUE THREAD

**Issue by nirmala-mist** [square/SocketRocket#224]
Hi 

I am trying to do wss and I see this error Assertion failed: (dispatch_get_specific((__bridge void *)self) == maybe_bridge(_workQueue)), function -[SRWebSocket assertOnWorkQueue]. Why is this occurring and how do I rectify the same?

**Comment by mikelikespie** [comment]
Hmm, could you provide a test case? Those assertions are there to make sure things are thread-safe.

**Comment by nirmala-mist** [comment]
Hi Mike
I was able to resolve the issue in the app using this library. Thanks

**Comment by emersonmalca** [comment]
Hi @mikelikespie, I can't reproduce the crash on my devices but it happened to Apple during review. Any indication on what could be causing it or how you fixed it? Thank you.

**Comment by iCaiP** [comment]
Hi,I have encountered this problem too. How did you solve it？
