### ISSUE TITLE
App store rejection

### ISSUE THREAD

**Issue by dillonykyang** [square/SocketRocket#226]
The use of _connect method in SRWebSocket.m is causing the app being rejected in the automated screening process during an app store submission.

Here's a reply from the Apple review team.
> This issue can occur if an app calls names that are similar to or directly calls our non-public APIs. It would be appropriate to remove all references to the selectors listed in the error message you received before resubmitting this app for review. I have verified that _connect shares a name with a private API and that it falls into this category of selectors.

**Comment by acorscadden** [comment]
Hmm, I haven't noticed this, and I've been submitting apps with SocketRocket pretty recently. I'll keep an eye on this.

**Comment by frobichaud** [comment]
Same issue here. Please mark #228 as a duplicate.

**Comment by klivin** [comment]
I am also getting this error while submitting app.  I was previously using test flight, but that went away last week so as people transfer to iTunes connect deployment, I imagine this issue will become very present...
I changed _connect to tempConnect to temporarily pass the rejection.

**Comment by fatuhoku** [comment]
+1 app store rejection on TestFlight here.

**Comment by nzeltzer** [comment]
As a general rule, it's probably just best to avoid prefixing method names with underscores:

_"Don’t use the underscore character as a prefix for your private methods. Apple reserves this convention."_ ([Apple/Coding Guidelines/Naming Methods](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingMethods.html))

**Comment by naartjie** [comment]
@dillonykyang Does this affect any specific versions of SocketRocket? I just had an app accepted which is using SocketRocket version 0.2.0.

**Comment by naartjie** [comment]
I just had a look at the source for the old 0.2.0 version which I am using, and `_connect` wasn't there. Instead there used to be a `_connectToHost` which was removed and replaced with `_connect` in this [commit](https://github.com/square/SocketRocket/commit/75fd01cb41bcbef5aa3235a4d2c3d9766b656048#diff-23371af810c948f5b65a136238d482e7L191).

@acorscadden please could you check which version SocketRocket you were using, thanks!

Apple are being petty here, but it's just a private method, and if a rename is all that is needed, then let's do that. It can just be called `connect` without the underscore surely?

**Comment by naartjie** [comment]
[PR](#238) submitted.

**Comment by mejiamariano** [comment]
Hi! Everyone, we got successfully deploy a new app with socketRocket Blumr for android, ios and web.

**Comment by erickreutz** [comment]
Running into this issue trying to upload our build to iTunes Connect today. Apple complains we are using non-public APIs. `_connect, _disconnect`.

**Comment by dfed** [comment]
Fixing this with #252. Thanks for bringing this to our attention!
