### ISSUE TITLE
XCode 6.3 beta warnings about extra semicolons in SRWebSocket.m 

### ISSUE THREAD

**Issue by jackpal** [square/SocketRocket#232]
When I compile SRWebSocket.m using XCode 6.3 I get numerous warnings of this form:

SRWebSocket.m:128:45: Semicolon before method body is ignored
SRWebSocket.m:138:45: Semicolon before method body is ignored

**Comment by dfed** [comment]
This issue has been resolved by Xcode fixing itself :)
