### ISSUE TITLE
_SR_commonInit -> EXC_BAD_ACCESS/KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by tettoffensive** [square/SocketRocket#235]
I've got an iOS app using SocketRocket and I noticed a couple crashes from our users in Parse that say `EXC_BAD_ACCESS / KERN_INVALID_ADDRESS` and the call stack seems a little random

The items that aren't `_SR_commonInit` don't have anything to do with SocketRocket so I don't know how to debug this really, I haven't seen it on my personal device. Though I did notice that line 337 has an `assert`

```
Thread 0 (crashed)
@ 0x1478a28
-[SRWebSocket _SR_commonInit] @ 0x24, SRWebSocket.m : 336
-[SRWebSocket _SR_commonInit] @ 0x24, SRWebSocket.m : 336
-[GDTextView handleTextViewDidChangeNotification:] @ 0x72, GDTextView.m : 72
-[SRWebSocket _SR_commonInit] @ 0x24, SRWebSocket.m : 336
-[CCNode(SFGestureRecognizers) addGestureRecognizer:] @ 0x1e, CCNode+SFGestureRecognizers.m : 298
```

Any ideas/suggestions?

**Comment by mikelikespie** [comment]
Hmm, could you provide a test case perhaps?
