### ISSUE TITLE
Receive didFailWithError, code 2132

### ISSUE THREAD

**Issue by chenlucan** [square/SocketRocket#259]
I was trying a simple example. WebSocket on iOS failed to connect to certain link, while it's working on web browser.

1. // working on both browser and iOS
NSString *urlString = @"wss://echo.websocket.org"; 

2. // only working on browser. iOS throw error didFailWithError, error code is 2132
NSString *urlString = @"wss://pubsub.pubnub.com/demo/demo/webrtc-app"; 

Someone suggest it's certificate problem. 
What's the reason it fails only on iOS? How to fix it?

**Comment by chenlucan** [comment]
I checked the http response error code, it's 404, which is strange. I could get valid response through websocket js

**Comment by devbriguy** [comment]
+1 I am also getting a similar error domain but with response code 400. Have you found a solution?

**Comment by chenlucan** [comment]
@devbriguy I didn't follow up this issue in my project any more. In case you're still working on this issue, I would suggest you try the latest version. Good luck!

Since this issue is open for quite long time with no response, I would close it. Feel free to open it again if it's necessary.
