### ISSUE TITLE
Apple rejects app due to _closeConnection, _openConnection usage

### ISSUE THREAD

**Issue by nickbit** [square/SocketRocket#263]
In short avoid to name methods as _xxx

**Comment by mk** [comment]
did you get rejected for those method names? We're thinking of updating SocketRocket and we'd be happy to provide a PR that changes the method names. Seems like #226 and it's PR #252 were meant to fix any app store issues.

**Comment by nickbit** [comment]
yes we got rejected for using those names. It seems that they use them also in some private framework and don't like for others to use them (they think we are using their private framework).

**Comment by mk** [comment]
thanks for letting me know! Probably best to remove any underscore prefixes from method names in SocketRocket then.

**Comment by kommen** [comment]
@brandons: Here you are: https://github.com/square/SocketRocket/pull/269

**Comment by brandons** [comment]
Can someone please merge this? No one using SocketRocket can submit their apps to the App Store.

@dnkoutso @dfed

**Comment by dfed** [comment]
version 0.4.1 has this fix.
