### ISSUE TITLE
how to identify whom user are chatting with another? 

### ISSUE THREAD

**Issue by agvasani9** [square/SocketRocket#295]
hello, sir. my requirement is : i am try the create multiple socket between all users. so how can i pass key and id such that server are divided in sepreation window.

Thank You.

**Comment by dfed** [comment]
This question is better suited for StackOverflow rather than a Github issue. When you write the question on StackOverflow, I recommend being much more specific as to what your use case is.

**Comment by agvasani9** [comment]
But, I think sir it's a major difficulty for me now. i thankful you, if you
help for solve my problem,
