### ISSUE TITLE
ERROR ITMS-90060

### ISSUE THREAD

**Issue by bitomule** [square/SocketRocket#302]
I get this error trying to publish my app:

````
ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString '0.3.1-beta2' in the Info.plist file must be a period-separated list of at most three non-negative integers."
````

Seems like name is invalid. What does beta 2 fixes, is it ready for production? I use socket rocket because I use ObjectiveDDP, how do I use a more stable version of Socket Rocket?

**Comment by hirad** [comment]
Same issue here.

**Comment by goktugyil** [comment]
https://github.com/Carthage/Carthage/issues/859
https://github.com/CocoaPods/CocoaPods/issues/4421

seems like everyone is having this issue

**Comment by dfed** [comment]
Why are you using 0.3.1-beta2? We're on v0.4.2, which shouldn't have this problem. Closing this issue out (though feel free to ask me to reopen if you have issues with the latest release).
