### ISSUE TITLE
[Bug] "websocket:didReceiveMessage" don't fired when connection secure

### ISSUE THREAD

**Issue by Messme** [square/SocketRocket#308]
Inner method "didConnect" don't fired at all.

**Comment by fjolnir** [comment]
This broke in https://github.com/square/SocketRocket/pull/231
If there are no pinned certificates, then the socket remains in "connecting" state forever.

**Comment by dfed** [comment]
Won't this break the issue #231 was fixing? Looks like we'll still connect before checking the cert.
