### ISSUE TITLE
Assertion failed on line 263

### ISSUE THREAD

**Issue by cemiltokatli** [square/SocketRocket#310]
I am trying to connect my socket server and getting this:

```Assertion failed: (request.URL), function -[SRWebSocket initWithURLRequest:protocols:], file /Users/username/Documents/ProjectName/Pods/SocketRocket/SocketRocket/SRWebSocket.m, line 263.```

I looked at the file and line. I guess something is wrong with this snippet:

![screen shot 2015-11-23 at 18 32 10](https://cloud.githubusercontent.com/assets/4648592/11342541/9536cc1a-9210-11e5-81f2-5a7bb22d69b8.png)

The only thing I am trying to do is initialize the object.

```SRWebSocket *newWebSocket = [[SRWebSocket alloc] initWithURL:[NSURL URLWithString:urlString]];```

What's wrong?

**Comment by kenwigginton** [comment]
@cemiltokatli according to the `NSURL` documentation, if your urlString is not a valid URL, `+ URLWithString:` will return nil. Please verify you're passing it a valid URL string.

https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSURL_Class/#//apple_ref/occ/clm/NSURL/URLWithString:`
