### ISSUE TITLE
crash when socket closes in background due to network disconnect

### ISSUE THREAD

**Issue by gauravsri** [square/SocketRocket#62]
When the App is running in background, I've seen a couple of crashes when SRWebSocket closes due to network failure.

Thread 19 Crashed:
0   CoreFoundation                      0x349d2202 CFEqual + 42
1   CoreFoundation                      0x34a42db9 __CFBagStandardEquateKeys + 37
2   CoreFoundation                      0x349d4b64 CFBasicHashRemoveValue + 1608
3   CoreFoundation                      0x34a00551 CFRunLoopRemoveSource + 341
4   CFNetwork                           0x30067a95 _CFTypeUnscheduleFromRunLoop + 285
5   CoreFoundation                      0x349d774d CFArrayApplyFunction + 177
6   CFNetwork                           0x30067963 Schedulables::unschedule(__CFRunLoop*, __CFString const*) + 39
7   CFNetwork                           0x30068375 SocketStream::close(void const*) + 57
8   CFNetwork                           0x300fa29b CoreStreamBase::_streamInterface_Close() + 47
9   CoreFoundation                      0x349e595f _CFStreamClose + 55
10  UCA Mobile for iPad                 0x000fa88d -[SRWebSocket _pumpWriting] (UCCWebSocket.m:1109)
11  UCA Mobile for iPad                 0x000f8eb7 __30-[SRWebSocket _failWithError:]_block_invoke_0 (UCCWebSocket.m:697)
12  libdispatch.dylib                   0x3133911f _dispatch_call_block_and_release + 11
13  libdispatch.dylib                   0x3133cecf _dispatch_queue_drain$VARIANT$mp + 143
14  libdispatch.dylib                   0x3133cdc1 _dispatch_queue_invoke$VARIANT$mp + 41
15  libdispatch.dylib                   0x3133d91d _dispatch_root_queue_drain + 185
16  libdispatch.dylib                   0x3133dac1 _dispatch_worker_thread2 + 85
17  libsystem_c.dylib                   0x31482a11 _pthread_wqthread + 361

**Comment by mikelikespie** [comment]
PLease co
