### ISSUE TITLE
Assertion failed: (aReadyState > _readyState)

### ISSUE THREAD

**Issue by nwalter08** [square/SocketRocket#75]
Sometimes when I disconnect I get this error that craches my app.

Assertion failed: (aReadyState > _readyState), function -[SRWebSocket setReadyState:]

SRWebSocket.m, line 379

**Comment by hamin** [comment]
@nwalter08 you still getting this crash?

**Comment by nwalter08** [comment]
Hey @hamin! I haven't run that code in a looooong time :) Sorry I'm no help.

**Comment by kirik** [comment]
Same here. I can't reproduce it manually, but sometimes it crashes my app..

**Comment by dfed** [comment]
This looks like a duplicate of #54. Let me know if you disagree.
