### ISSUE TITLE
Implicit conversion of Objective-C pointer type

### ISSUE THREAD

**Issue by joecarney** [square/SocketRocket#76]
Just dropped the latest SocketRocket into my iPhone project... and it is no longer compiling...

SRWebSocket.m:47:25: Implicit conversion of Objective-C pointer type 'dispatch_queue_t' (aka 'NSObject<OS_dispatch_queue> *') to C pointer type 'void *' requires a bridged cast

SRWebSocket.m:373:5: Implicit conversion of Objective-C pointer type 'dispatch_queue_t' (aka 'NSObject<OS_dispatch_queue> *') to C pointer type 'void *' requires a bridged cast

When I try the 'fixes' that xcode recommends, it makes it worse...

Any ideas?

**Comment by mikelikespie** [comment]
Doing some housekeeping. Please reopen if still relevant
