### ISSUE TITLE
EXC_BAD_ACCESS in SRWebSocket_HTTPHeadersDidFinish

### ISSUE THREAD

**Issue by HaKop** [square/SocketRocket#79]
Hello,
i'm always getting an error (see picture) while trying to establish a websocket connection.
my target is ios 6.0, using ARC and this is my code:

    NSURL* url = [[NSURL alloc] initWithString:uriString];
    webSocket = [[SRWebSocket alloc] initWithURL:url];
    webSocket.delegate = self;
    [webSocket open];

![error](https://f.cloud.github.com/assets/1029917/167236/b31b35ba-79ca-11e2-8e6a-6ab66d35386a.png)

**Comment by mikelikespie** [comment]
Doing some housekeeping. Please reopen if still relevant
