### ISSUE TITLE
Targetting 10.6/10.7

### ISSUE THREAD

**Issue by natevw** [square/SocketRocket#83]
I was able to successfully compile SocketRocket for 10.6 simply by changing the deployment target from 10.8 to 10.6. It's my understanding that ARCLite should take care of most of the core differences, unless the code relies on zeroing weak references.

Would you be interested in pull requests relevant to older OS X versions that may be easy to support? I'm using this in a project that doesn't necessarily need to work on 10.6 but am aiming for that unless we find a significant hurdle.

One such hurdle would be having to maintain a stale fork of a library that really prefers to support only newer versions ;-)

**Comment by mikelikespie** [comment]
Doing some housekeeping. Please reopen if still relevant
