### ISSUE TITLE
Able to send Multiple HTTP Requests but unable to get response of those HTTP request on TCP socket created

### ISSUE THREAD

**Issue by Anshumakkar** [square/SocketRocket#85]
I want to send an HTTP request to HTTP server and then after getting successful response I want to upgrade connection to upgrade if the response is bad in previous request I do not want to upgrade the connection. The scenario is as
1.Open TCP socket
2.Send an HTTP REQUEST
3.If the response is 202, we will send a HTTP request to upgrade the connection to web socket
4. The response code expected is 101(Response phrase-SWITCHING PROTOCOLS)
but the response obtained is null. 

I've observe the traces on Wireshark on server and client side. THe server is sending 101/Switching Protocols and on i-Mac the response is 101 on wireshark but in simulator it is not 101 it is 200 with response null. 

Please help

**Comment by mikelikespie** [comment]
Please elaborate.
