### ISSUE TITLE
Stream end encountered

### ISSUE THREAD

**Issue by kevinvavelin** [square/SocketRocket#92]
Hi there,

I see there is another thread called like mine which is closed (https://github.com/square/SocketRocket/issues/82) but I've the same issue with the use of this project (https://github.com/pkyeck/socket.IO-objc).

The stream closed after a connexion with Facebook, where I send my accessToken and many data to my socket.io server and when I get my data back and do nothing else, my connexion closed.

Can you help me with ?

**Comment by dfed** [comment]
Doing some housekeeping. Please reopen if still relevant

**Comment by smolskyaleksey** [comment]
I still have this issue. I received  "Socket did open" after that "Socket did close with code: 1001; reason: Stream end encountered; was clean: No."

**Comment by mikeKane** [comment]
Im seeing close with code 0 as well. What would cause the error code 0?

**Comment by michaelluk** [comment]
@kevinvavelin Have you figured out what's the problem? I am using the same framework(https://github.com/pkyeck/socket.IO-objc) as you did and could you give me some hints on how you solve the problem? I am getting the weird NSStreamEventEndEncountered and the websocket disconnected with error after few rounds of normal communication with my server.  Thanks :)

**Comment by manish-1988** [comment]
I am getting the same error 

`2016-07-19 14:15:03.901 VideoCallingAppRTC[315:21955] WebSocket closed with code: 1001 reason:Stream end encountered wasClean:0
2016-07-19 14:15:03.901 VideoCallingAppRTC[315:21955] C->RS: BYE
2016-07-19 14:15:03.901 VideoCallingAppRTC[315:21955] url = https://apprtc.appspot.com/leave/gsdtest103/52754944
Disconnected!
2016-07-19 14:15:05.084 VideoCallingAppRTC[315:21955] Unregistered from room server.
`

**Comment by gitkong** [comment]
same problem :Closed Reason:Stream end encountered  code = 1001,i dont know how to do now

**Comment by mobilestar2015** [comment]
Same problem. Stream end encountered code = 1001,.
I am getting this error while testing Kurento-iOS, it's closed while sending icecandidates to the server.
I can't figure out the reason. Please help me.

**Comment by gunjotSinghMansa** [comment]
I am facing the same issue "didCloseWithCode --> 1001 and reason ==> Stream end encountered", but only while using 4G connection. It works perfect with my wifi!

**Comment by protspace** [comment]
I am facing the same issue

**Comment by gunjotSinghMansa** [comment]
For me, only working solution is to send ping to server after every second to sustain connection in case using 4G.

**Comment by notedit** [comment]
i am faceing this  problom,  my python websocekt client can work well.

**Comment by Dendim0n** [comment]
Code:1001 
Reason:Stream end encountered

**Comment by vysotskiyserhiy** [comment]
Code:1001
Reason:Stream end encountered

**Comment by qbshen** [comment]
when connect Socket.io , you should append "/socket.io/?EIO=4&transport=websocket", good luck!

**Comment by qbshen** [comment]
when connect Socket.io , you should append "ws://ip:port/socket.io/?EIO=4&transport=websocket", good luck!

**Comment by AutumnSky** [comment]
@qbshen Wow! It works to me! Thank you. BTW, Where this option from? and What does this option doing for Connection? Please give me any hint.

**Comment by jose920405** [comment]
@qbshen 

My error was 

```
Code:1001
Reason:Stream end encountered
```

Using `/socket.io/?EIO=4&transport=websocket`

My logs

```
onopen >>>>>>>
'onmessage', '0{"sid":"WAKpVjnwpgUSuz8OAAAD","upgrades":[],"pingInterval":25000,"pingTimeout":60000}'
'onmessage', '40'
'onclose ==> ', 1005, null
```

**Comment by Piasy** [comment]
I faced the same issue today, and I figured out that it was because I didn't specify sub protocols, which caused server closing the connection.

**Comment by AlphaJian** [comment]
@Piasy I met the same issue. Could you please tell me which sub protocols do you specify?

**Comment by Piasy** [comment]
I was connecting to [Janus Gateway](https://github.com/meetecho/janus-gateway)'s via websocket, it need set `janus-protocol` as sub protocol.

**Comment by huntergai** [comment]
俺也一样

**Comment by huntergai** [comment]
俺也一样的问题，拼接了也不好使。有没有其他的解决办法

**Comment by tshradheya** [comment]
Any help on this? Not using sockeet io. Using react native websockets

**Comment by yigegongjiang** [comment]
Me too : (

**Comment by maxhawkins** [comment]
I solved this issue by sending a [keepalive ping](https://tools.ietf.org/html/rfc6455#section-5.5.2) every once in a while.

My WebSocket connection was proxied through nginx which times out the WebSocket after 60 seconds without receiving a message.

From React Native:
```js
setInterval(() => ws.ping(), 30000);
```
